const app=document.getElementById("app"),drawer=document.getElementById("drawer"),drawerContent=document.getElementById("drawerContent"),scrim=document.getElementById("scrim");
const state={view:"today",last:null,needs:[
{id:"students",source:"U Tampa · ENT 330",title:"Two students may need outreach",detail:"A text question and declining Live Classroom participation point to the same assignment confusion.",why:"Waiting until next week could allow both students to fall further behind.",deadline:"Before 2 PM",effort:"8 min",action:"Open drafts",terminal:false,fresh:"Canvas + Live Classroom · 9:18 AM"},
{id:"record",source:"Entrepreneurship Professor",title:"Record the media response",detail:"The small-business confidence story is still timely; your prepared script is ready.",why:"Recording before 2 PM preserves the same-day publishing window.",deadline:"2 PM",effort:"12 min",action:"Start recording",terminal:false,fresh:"Story Radar · 10:06 AM"},
{id:"calculator",source:"Family · Hero",title:"Approve the calculator request",detail:"Hero needs a replacement calculator for Friday’s class.",why:"Approving now lets BOS add it to today’s household order.",deadline:"Today",effort:"1 min",action:"Approve request",terminal:true,fresh:"Bert-provided request · 8:42 AM"},
{id:"mentor",source:"U Tampa · Spartan Incubator",title:"Confirm a mentor introduction",detail:"A founder match is ready based on retail-operations experience.",why:"Approval today keeps the introduction ahead of Wednesday’s meeting.",deadline:"Today",effort:"3 min",action:"Approve intro",terminal:true,fresh:"Incubator records · Yesterday"},
{id:"manuscript",source:"U Tampa · Research",title:"Review coauthor changes",detail:"A short review keeps the manuscript on track for Friday.",why:"Waiting creates a three-day delay in the writing sequence.",deadline:"Friday",effort:"12 min",action:"Open manuscript",terminal:false,fresh:"Google Drive · 9:02 AM"}]};
const schedule=[
{t:"8:00",title:"ENT 330 · Live class",meta:"Sykes 134 · 75 min",type:"meeting",action:"meeting"},
{t:"10:00",title:"Office hours",meta:"Two student appointments",type:"meeting",action:"meeting"},
{t:"12:30",title:"Spartan Incubator",meta:"Internships + founder blockers",type:"meeting",action:"meeting"},
{t:"3:15",title:"Pick up Liv",meta:"Leave by 2:52 · traffic is building",type:"family-event alert-event",action:"route"},
{t:"4:00",title:"Instacart delivery window",meta:"7 recurring items ready for review",type:"family-event",action:"groceries"},
{t:"6:15",title:"Family dinner",meta:"Hero sets · Liv clears · Albert sweeps",type:"family-event",action:"chores"}];
const handling=[["ENT 330 class prep","Ready for review","92%"],["Content story angles","3 drafts by 1:15 PM","68%"],["Incubator agenda","Waiting on one founder update","76%"],["Promises reconciliation","12 captured · 2 need review","84%"]];
function intro(sub){return '<section class="intro"><div><div class="eyebrow">Today · one life, one priority order</div><h1>Good morning, Bert.</h1><p>'+(sub||"BOS combined your university, business, and family context into one plan.")+'</p></div><span class="prototype">Interactive design · sample data</span></section>'}
function briefing(){return '<section class="briefing"><button class="brief-icon" data-audio aria-label="Play briefing">▶</button><div><strong>Your day is workable, with one pressure point.</strong><p>Handle the student outreach and media response before lunch. Leave by 2:52 for Liv; BOS protected the rest of the afternoon.</p></div></section>'}
function eventActions(e,i){if(e.action==="meeting")return '<button class="btn" data-prepare="'+i+'">Prepare me</button><button class="btn iconbtn" data-audio aria-label="Play 30-second brief">▶</button>';if(e.action==="route")return '<button class="btn" data-event="'+i+'">View route</button>';if(e.action==="groceries")return '<button class="btn" data-grocery>Review order</button>';return '<button class="btn" data-chores>View chores</button>'}
function timeline(){return '<div class="timeline">'+schedule.map(function(e,i){return '<div class="event '+e.type+'"><div class="time">'+e.t+'</div><span class="event-dot"></span><div><strong>'+e.title+'</strong><span class="meta">'+e.meta+'</span></div><div class="event-actions">'+eventActions(e,i)+'</div></div>'}).join("")+'</div>'}
function needCard(n){const i=state.needs.indexOf(n);return '<article class="need"><span class="source">'+n.source+'</span><h3>'+n.title+'</h3><p>'+n.detail+'</p><div class="facts"><span class="fact"><strong>'+n.deadline+'</strong> deadline</span><span class="fact"><strong>'+n.effort+'</strong> effort</span></div><div class="actions"><button class="btn primary" data-need="'+i+'">'+n.action+'</button><button class="btn" data-detail="'+i+'">Details</button></div></article>'}
function commitments(){return '<div class="compact-list"><div class="compact-row"><span class="round-icon">R</span><div><strong>Send Rebecca the incubator update</strong><span class="meta">Promised in yesterday’s meeting</span></div><span class="status">Today</span></div><div class="compact-row"><span class="round-icon">A</span><div><strong>Anna’s project scope</strong><span class="meta">BOS drafting · review at 1:15 PM</span></div><span class="status good">Delegated</span></div><div class="compact-row"><span class="round-icon">M</span><div><strong>Mentor availability</strong><span class="meta">Waiting on Monica · follow up Monday</span></div><span class="status good">Waiting</span></div></div>'}
function family(){return '<div class="compact-list"><div class="compact-row"><span class="round-icon orange">L</span><div><strong>Liv pickup timing changed</strong><span class="meta">Leave by 2:52 PM</span></div><button class="linkbtn" data-event="3">Route</button></div><div class="compact-row"><span class="round-icon orange">H</span><div><strong>Hero’s calculator request</strong><span class="meta">Awaiting approval</span></div><button class="linkbtn" data-family-request>Review</button></div><div class="compact-row"><span class="round-icon orange">✓</span><div><strong>Responsibilities: 5 of 7 complete</strong><span class="meta">1 due by 6:00 · 1 blocked</span></div><button class="linkbtn" data-chores>View</button></div><div class="compact-row"><span class="round-icon orange">G</span><div><strong>Household order ready</strong><span class="meta">7 recurring items · approval required</span></div><button class="linkbtn" data-grocery>Review</button></div></div>'}
function exceptions(){return '<section class="card exception-strip"><div class="strip-title">BOS noticed</div><div class="exception" data-ex><span>Schedule risk</span><strong>Leave by 2:52 PM</strong><p>Traffic adds 11 minutes to Liv’s pickup.</p></div><div class="exception opportunity" data-ex><span>Opportunity</span><strong>Founder signed first pilot</strong><p>Add the win to Wednesday’s agenda or prepare a post.</p></div><div class="exception" data-ex><span>Could slip</span><strong>ENT 487 module review</strong><p>15 minutes today protects Tuesday’s release.</p></div></section>'}
function handlingBox(){return '<section class="card handling-summary"><div class="cardhead"><div><h2>BOS is handling</h2><span class="subtle">Healthy work stays quiet; ready or blocked work rises here.</span></div><button class="linkbtn" data-view="handling">Open work queue →</button></div><div class="handling-grid">'+handling.map(function(x,i){return '<div class="handling-item" data-handling="'+i+'"><strong>'+x[0]+'</strong><span>'+x[1]+'</span><div class="progress"><i style="width:'+x[2]+'"></i></div></div>'}).join("")+'</div></section>'}
function renderToday(){app.innerHTML=intro()+briefing()+'<div class="top-grid"><section class="card"><div class="cardhead"><div><h2>Your day, interpreted</h2><span class="subtle">Work, family, travel, and preparation</span></div><button class="linkbtn" data-view="calendar">Full calendar →</button></div>'+timeline()+'</section><section class="card"><div class="cardhead"><div><h2>What needs you</h2><span class="subtle">Ranked across every part of life</span></div><span class="status">'+state.needs.length+' waiting</span></div><div class="needs">'+state.needs.slice(0,3).map(needCard).join("")+'</div><div class="rotator-note">Complete one and the next priority moves up.</div></section></div>'+exceptions()+'<div class="lower-grid"><section class="card"><div class="cardhead"><div><h2>Promises & loose ends</h2><span class="subtle">Things BOS will not let disappear</span></div><button class="linkbtn" data-view="commitments">All →</button></div>'+commitments()+'</section><section class="card"><div class="cardhead"><div><h2>Family & home</h2><span class="subtle">Only exceptions and approvals</span></div><button class="linkbtn" data-view="family">Open →</button></div>'+family()+'</section></div>'+handlingBox();bind()}
function rows(title,items){return '<section class="card"><div class="cardhead"><h2>'+title+'</h2><button class="btn">Filter</button></div><div class="rows">'+items.map(function(r,i){return '<div class="row"><div><h3>'+r[0]+'</h3><p>'+r[1]+'</p></div><button class="btn '+(i?"":"primary")+'" data-row="'+r.join("|")+'">'+r[2]+'</button></div>'}).join("")+'</div></section>'}
function renderPriorities(){app.innerHTML=intro("Every item requiring your judgment, ranked by urgency, impact, effort, and consequence.")+'<section class="card"><div class="cardhead"><h2>Needs Bert</h2><span class="status">Ranked by BOS</span></div><div class="needs">'+(state.needs.map(needCard).join("")||'<div class="empty">Nothing needs you right now.</div>')+'</div></section>';bind()}
function renderCalendar(){app.innerHTML=intro("Work and family calendar interpreted with preparation, travel, and conflicts.")+'<section class="card"><div class="cardhead"><h2>Friday</h2><span class="status">One pressure point</span></div>'+timeline()+'</section>';bind()}
function renderProjects(){app.innerHTML=intro("Projects appear by outcome and intervention—not as a generic progress chart.")+rows("Project portfolio",[["ENT 487 course release","Target Tuesday · On track if reviewed today","Review module"],["Research manuscript","Target Friday · 82% confidence","Open manuscript"],["Spartan Incubator internships","Two role descriptions could slip","Intervene"],["EP content engine","Media response ready · publishing window 2 PM","Record"]]);bind()}
function renderFamily(){app.innerHTML=intro("Schedules, responsibilities, requests, groceries, and household routines—with no financial dashboard.")+'<div class="tabs"><button class="active">Overview</button><button>Family calendar</button><button>Kids & responsibilities</button><button>Household</button><button>Groceries</button></div><div class="page-grid"><section class="card"><div class="cardhead"><h2>Family needs attention</h2><span class="status">3 exceptions</span></div>'+family()+'</section><section class="card"><div class="cardhead"><h2>Today’s responsibilities</h2><span class="subtle">5 of 7 complete</span></div><div class="metric-line"><span>Albert · Sweep after dinner</span><span class="status">Due 7 PM</span></div><div class="metric-line"><span>Hero · Set table</span><span class="status good">Claimed</span></div><div class="metric-line"><span>Liv · Put library book in bag</span><span class="status late">Blocked</span></div><button class="btn" data-chores style="margin-top:12px">Open chore details</button></section><section class="card"><div class="cardhead"><h2>Next family transition</h2><span class="subtle">Tuesday</span></div><p>Everything is ready except Liv’s library book. BOS surfaces only missing handoff items.</p><button class="btn">View checklist</button></section><section class="card"><div class="cardhead"><h2>Groceries & household</h2><span class="status">Approval required</span></div><p>Recurring essentials and family requests are assembled. BOS never places an order without approval.</p><button class="btn orange" data-grocery>Review proposed cart</button></section></div>';bind()}
function renderCommitments(){app.innerHTML=intro("Relationships, promises, and waiting states remain visible across every system.")+rows("People & commitments",[["Rebecca","Incubator update promised yesterday","Prepare update"],["Monica","Mentor availability · waiting on response","View context"],["Anna","Project scope · BOS draft ready 1:15 PM","Review draft"],["ENT 330 students","Two outreach drafts waiting on you","Open drafts"]]);bind()}
function renderMessages(){app.innerHTML=intro("Only messages that may change a decision, action, or relationship appear here.")+rows("Messages that matter",[["Student text · ENT 330","May indicate broader assignment confusion","Open with context"],["Founder update","First pilot customer signed this morning","Add to agenda"],["School reminder · Liv","Library book due tomorrow","Add to handoff"]]);bind()}
function renderHandling(){app.innerHTML=intro("Autonomous work shows its next checkpoint, expected completion, and blockers.")+rows("BOS work queue",handling.map(function(x){return [x[0],x[1]+" · "+x[2],"Review"]}));bind()}
const views={today:renderToday,priorities:renderPriorities,calendar:renderCalendar,projects:renderProjects,family:renderFamily,commitments:renderCommitments,messages:renderMessages,handling:renderHandling};
function openDrawer(html,trigger){drawerContent.innerHTML=html;drawer.classList.add("open");scrim.classList.add("open");drawer.setAttribute("aria-hidden","false");state.trigger=trigger;document.getElementById("closeDrawer").focus()}
function closePanel(){drawer.classList.remove("open");scrim.classList.remove("open");drawer.setAttribute("aria-hidden","true");if(state.trigger)state.trigger.focus()}
function toast(msg,undo){toastText.textContent=msg;document.getElementById("toast").classList.toggle("can-undo",!!undo);document.getElementById("toast").classList.add("show");clearTimeout(state.timer);state.timer=setTimeout(function(){document.getElementById("toast").classList.remove("show")},3500)}
function detail(n,t){openDrawer('<div class="eyebrow">'+n.source+'</div><h2>'+n.title+'</h2><p>'+n.detail+'</p><div class="detail-grid"><div><span>Deadline</span><strong>'+n.deadline+'</strong></div><div><span>Estimated effort</span><strong>'+n.effort+'</strong></div></div><div class="detail-block"><strong>Why BOS surfaced this</strong><p>'+n.why+'</p></div><div class="detail-block"><strong>Source and freshness</strong><p>'+n.fresh+'</p></div><button class="btn primary" data-drawer-action>'+n.action+'</button>',t);drawerContent.querySelector("[data-drawer-action]").onclick=function(){handleNeed(state.needs.indexOf(n))}}
function handleNeed(i){const n=state.needs[i];if(!n)return;if(n.terminal){state.needs.splice(i,1);state.last={n:n,i:i};closePanel();views[state.view]();toast(n.title+" — completed",true)}else{openDrawer('<div class="eyebrow">'+n.source+'</div><h2>'+n.action+'</h2><p>Opening work does not complete it or remove it from Needs Bert.</p><div class="detail-block"><strong>Still waiting on you</strong><p>Mark handled only after the real work is complete.</p></div><button class="btn primary" data-mark>Mark handled</button>',document.activeElement);drawerContent.querySelector("[data-mark]").onclick=function(){const j=state.needs.findIndex(function(x){return x.id===n.id});if(j>-1){state.needs.splice(j,1);state.last={n:n,i:j}}closePanel();views[state.view]();toast(n.title+" — marked handled",true)}}}
function prepare(i,t){const e=schedule[i];openDrawer('<div class="eyebrow">Prepare me</div><h2>'+e.title+'</h2><p>'+e.t+' · '+e.meta+'</p><div class="detail-block"><strong>What this is about</strong><p>BOS assembled relevant calendar context, notes, messages, and open commitments.</p></div><div class="detail-block"><strong>Your objectives</strong><p>Resolve the key question, confirm ownership, and capture new promises.</p></div><div class="actions"><button class="btn primary" data-doc>Open preparation document</button><button class="btn" data-play>▶ Play 30-second brief</button></div>',t);drawerContent.querySelector("[data-doc]").onclick=function(){toast("Preparation document opened")};drawerContent.querySelector("[data-play]").onclick=function(){toast("Playing meeting briefing…")}}
function groceries(t){openDrawer('<div class="eyebrow">Family & home</div><h2>Review proposed Instacart cart</h2><p>BOS assembled recurring essentials and family requests. No order is placed without approval.</p><div class="detail-block"><strong>7 recurring essentials</strong><p>Milk, eggs, bananas, sandwich bread, yogurt, cereal, and sparkling water.</p></div><div class="detail-block"><strong>Approval safeguard</strong><p>Review substitutions and delivery window before approving. Spending trends are excluded.</p></div><div class="actions"><button class="btn">Edit items</button><button class="btn orange" data-order>Approve order</button></div>',t);drawerContent.querySelector("[data-order]").onclick=function(){closePanel();toast("Order approved · delivery confirmation pending")}}
function chores(t){openDrawer('<div class="eyebrow">Kids & responsibilities</div><h2>Today’s household responsibilities</h2><p>5 of 7 complete · 1 due by 6:00 · 1 blocked</p><div class="detail-block"><strong>Liv · Put library book in bag</strong><p><span class="status late">Blocked</span> Book location unknown; this affects tomorrow’s handoff.</p></div><div class="detail-block"><strong>Albert · Sweep after dinner</strong><p><span class="status">Due 7 PM</span> Recurring Friday responsibility.</p></div><div class="detail-block"><strong>Method</strong><p>Upcoming → Due → Claimed → Done → Verified when needed. BOS escalates only blocked, late, disputed, or repeatedly missed responsibilities.</p></div><button class="btn primary">Send reminder</button>',t)}
function bind(){document.querySelectorAll("[data-view]").forEach(function(b){b.onclick=function(){go(b.dataset.view)}});document.querySelectorAll("[data-need]").forEach(function(b){b.onclick=function(){handleNeed(+b.dataset.need)}});document.querySelectorAll("[data-detail]").forEach(function(b){b.onclick=function(){detail(state.needs[+b.dataset.detail],b)}});document.querySelectorAll("[data-prepare]").forEach(function(b){b.onclick=function(){prepare(+b.dataset.prepare,b)}});document.querySelectorAll("[data-audio]").forEach(function(b){b.onclick=function(){toast("Playing your 30-second briefing…")}});document.querySelectorAll("[data-grocery]").forEach(function(b){b.onclick=function(){groceries(b)}});document.querySelectorAll("[data-chores]").forEach(function(b){b.onclick=function(){chores(b)}});document.querySelectorAll("[data-family-request]").forEach(function(b){b.onclick=function(){const i=state.needs.findIndex(function(n){return n.id==="calculator"});if(i>-1)detail(state.needs[i],b);else toast("This request has been handled.")}});document.querySelectorAll("[data-event]").forEach(function(b){b.onclick=function(){openDrawer('<div class="eyebrow">Schedule intelligence</div><h2>Leave by 2:52 PM</h2><p>Current traffic adds 11 minutes to Liv’s pickup.</p><button class="btn primary">Open route</button>',b)}});document.querySelectorAll("[data-ex]").forEach(function(b){b.onclick=function(){openDrawer('<div class="eyebrow">BOS noticed</div><h2>'+b.querySelector("strong").textContent+'</h2><p>'+b.querySelector("p").textContent+'</p><div class="detail-block"><strong>Why it appears here</strong><p>This changes a decision, schedule, or opportunity. Passive status stays in the originating dashboard.</p></div><button class="btn primary">Take recommended action</button>',b)}});document.querySelectorAll("[data-handling]").forEach(function(b){b.onclick=function(){const x=handling[+b.dataset.handling];openDrawer('<div class="eyebrow">BOS is handling</div><h2>'+x[0]+'</h2><p>'+x[1]+'</p><div class="detail-block"><strong>Next checkpoint</strong><p>BOS notifies you only when ready, blocked, or requiring a decision.</p></div><button class="btn danger">Pause</button>',b)}});document.querySelectorAll("[data-row]").forEach(function(b){b.onclick=function(){const r=b.dataset.row.split("|");openDrawer('<div class="eyebrow">Workspace</div><h2>'+r[0]+'</h2><p>'+r[1]+'</p><div class="detail-block"><strong>Recommended next move</strong><p>'+r[2]+'</p></div><div class="detail-block"><strong>Source</strong><p>Sample prototype data · production destination required</p></div><button class="btn primary">'+r[2]+'</button>',b)}})}
function go(v){state.view=v;document.querySelectorAll(".section-nav [data-view]").forEach(function(b){b.classList.toggle("active",b.dataset.view===v)});views[v]();window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-os]").forEach(function(b){b.onclick=function(){if(b.dataset.os==="bos")go("today");else openDrawer('<div class="eyebrow">Operating system</div><h2>'+(b.dataset.os==="utampa"?"UTampa":"Entrepreneurship Professor")+'</h2><p>In production, this shared header opens the dedicated dashboard. BOS brings back only its highest-priority actionable items.</p><button class="btn primary">Open dashboard</button>',b)}});
voiceBtn.onclick=function(){recording.classList.add("open")};stopRecording.onclick=function(){recording.classList.remove("open");toast("Captured. Review transcript before BOS routes it.")};cancelRecording.onclick=function(){recording.classList.remove("open")};globalBrief.onclick=function(){prepare(2,globalBrief)};recordMeeting.onclick=function(){toast("Meeting recording started · prototype")};searchBtn.onclick=function(){openDrawer('<div class="eyebrow">Search everything</div><h2>Find anything BOS knows</h2><p>Search verified sources, context, projects, messages, people, and commitments.</p><input aria-label="Search" style="width:100%;padding:12px;border:1px solid #dce7f0;border-radius:9px;font:inherit" placeholder="Search people, projects, promises…">',searchBtn)};closeDrawer.onclick=closePanel;scrim.onclick=closePanel;undoBtn.onclick=function(){if(state.last){state.needs.splice(state.last.i,0,state.last.n);state.last=null;views[state.view]();toast("Action restored")}};document.addEventListener("keydown",function(e){if(e.key==="Escape"){recording.classList.remove("open");closePanel()}});
function updateGlobalAlert(){const now=Date.now(),start=Date.parse(globalAlert.dataset.start),end=Date.parse(globalAlert.dataset.end),active=now>=start&&now<=end;globalAlert.classList.toggle("inactive",!active);document.documentElement.style.setProperty("--section-top",active?"140px":"88px")}
handleGlobalAlert.onclick=function(){openDrawer('<div class="eyebrow">Time-sensitive media opportunity</div><h2>Media response window</h2><p>Your prepared response is ready. Recording before 2:00 PM preserves the current publishing window.</p><div class="detail-block"><strong>Appears across every dashboard</strong><p>This global alert remains visible in BOS, U Tampa, and Entrepreneurship Professor only during its scheduled window.</p></div><div class="actions"><button class="btn primary">Open prepared response</button><button class="btn orange">Start recording</button></div>',handleGlobalAlert)};updateGlobalAlert();setInterval(updateGlobalAlert,60000);go("today");
